# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
b=User.create!(username: 'bananabb', password: "acffff")
Icebreaker.create!(content: "What fictional family would you most like to join?", filled: true, user_id: b.id, tags: "media, pop culture, television" )
Icebreaker.create!(content: "Do you love working from home or would you rather be in the office? Is there a balance of both that you like best?" , filled: true, user_id: b.id, tags: "remote, virtual, WFH" )
Icebreaker.create!(content: "What’s your number one tip for combating distractions when working from home?", filled: true, user_id: b.id, tags: "remote, virtual, WFH, motivation" )
Icebreaker.create!(content: "What’s the last great TV show or movie you watched?", filled: true, user_id: b.id, tags: "remote, virtual, television, pop culture" )
Icebreaker.create!(content: "What is your most used emoji?", filled: true, user_id: b.id, tags: "remote, pop culture, communication, funny" )
Icebreaker.create!(content: "If you were a wrestler what would be your entrance theme song?", filled: true, user_id: b.id, tags: "pop culture, media, funny" )
Icebreaker.create!(content: "If you could bring back any fashion trend what would it be?", filled: true, user_id: b.id, tags: "pop culture, fashion, trends" )
Icebreaker.create!(content: "You have your own late night talk show, who do you invite as your first guest?", filled: true, user_id: b.id, tags: "pop culture, media, funny" )
Icebreaker.create!(content: "If you had to eat one meal everyday for the rest of your life what would it be?", filled: true, user_id: b.id, tags: "funny, childhood, favorites")
Icebreaker.create!(content: "If you were left on a deserted island with either your worst enemy or no one, which would you choose? Why?", filled: true, user_id: b.id , tags: "funny, would you rather")
Icebreaker.create!(content: "What’s the best piece of advice you’ve ever been given?", filled: true, user_id: b.id, tags: "work, teamwork, motivation" )
Icebreaker.create!(content: "What would the title of your autobiography be?", filled: true, user_id: b.id, tags: "remote, literature, motivation" )
Icebreaker.create!(content: "Who is your favorite Disney hero or heroine? Would you trade places with them?", filled: true, user_id: b.id, tags: "pop culture, media, childhood" )
Icebreaker.create!(content: "What languages do you know how to speak?", filled: true, user_id: b.id, tags: "basic, work" )
Icebreaker.create!(content: "Are you a cat person or a dog person?", filled: true, user_id: b.id, tags: "basic, animals, would you rather" )
Icebreaker.create!(content: "You can have an unlimited supply of one thing for the rest of your life, what is it? Sushi? Scotch Tape?", filled: true, user_id: b.id, tags: "WWYD, unusual, funny" )
Icebreaker.create!(content: "If you could live anywhere in the world for a year, where would it be?", filled: true, user_id: b.id , tags: "if you could, work")
Icebreaker.create!(content: "If you could choose any two famous people to have dinner with who would they be?", filled: true, user_id: b.id, tags: "if you could, pop culture, media, history" )
Icebreaker.create!(content: "If you could be any animal in the world, what animal would you choose to be?", filled: true, user_id: b.id, tags: "if you could, favorites, animals" )
Icebreaker.create!(content: "If you could instantly become an expert in something, what would it be?", filled: true, user_id: b.id, tags: "if you could, work, motivation" )
Icebreaker.create!(content: "Would you rather live in the ocean or on the moon?", filled: true, user_id: b.id, tags: "would you rather, funny, life" )
Icebreaker.create!(content: "Would you rather meet your travel back in time to meet your ancestors or to the future to meet your descendants?", filled: true, user_id: b.id, tags: "would you rather, family, life" )
Icebreaker.create!(content: "Would you rather live where it only snows or the temperature never falls below 100 degrees?", filled: true, user_id: b.id, tags: "would you rather, basic, life" )
Icebreaker.create!(content: "Did you attend college? What was your major, or what would it have been?", filled: true, user_id: b.id, tags: "history, life, potentially sensitive" )
Icebreaker.create!(content: "What was your dream job when you were a kid?", filled: true, user_id: b.id, tags: "childhood, history, work" )
Icebreaker.create!(content: "Are there any interesting things your name spells with the letters rearranged?", filled: true, user_id: b.id, tags: "PIDK, general" )
Icebreaker.create!(content: "On what reality show would you most like to appear?", filled: true, user_id: b.id, tags: "if you could, pop culture, PIDK" )
Icebreaker.create!(content: " Which of Snow White’s seven dwarfs describes you best (Bashful, Doc, Dopey, Grumpy, Happy, Sleepy or Sneezy)?", filled: true, user_id: b.id, tags: "pop culture, personality" )
Icebreaker.create!(content: "Are you a listener or a talker?", filled: true, user_id: b.id, tags: "would you rather, personality" )
Icebreaker.create!(content: "If you could only listen to one album for the rest of your life, what would it be?", filled: true, user_id: b.id, tags: "if you could, favorites, music" )
Icebreaker.create!(content: "What was the worst movie you’ve ever watched?", filled: true, user_id: b.id, tags: "favorites, pop culture, media, PIDK" )
Icebreaker.create!(content: "Would you rather have invisibility or flight?", filled: true, user_id: b.id, tags: "would you rather, super powers")
Icebreaker.create!(content: "Would you prefer to always be slightly late or always be an hour early?", filled: true, user_id: b.id, tags: "would you rather, personality" )
Icebreaker.create!(content: "What was your first job?", filled: true, user_id: b.id, tags: "personality, history, basic" )
Icebreaker.create!(content: "What year would you visit if you had a time machine?", filled: true, user_id: b.id, tags: "if you could, history, PIDK" )
Icebreaker.create!(content: "What's your favorite breakfast cereal or breakfast food?", filled: true, user_id: b.id, tags: "favorites, basic" )
Icebreaker.create!(content: "What’s something new or interesting you’ve learned recently?", filled: true, user_id: b.id, tags: "personality, history, basic" )
Icebreaker.create!(content: "If you could safely eat any inedible object, what would it be?", filled: true, user_id: b.id, tags: "funny, personality, PIDK" )
Icebreaker.create!(content: "If you did not have to sleep, how would you spend the extra 8 hours?", filled: true, user_id: b.id, tags: "basic, personality, PIDK" )
Icebreaker.create!(content: "What season would you be? Why?", filled: true, user_id: b.id, tags: "basic, personality" )
Icebreaker.create!(content: "If you did not have to sleep, how would you spend the extra 8 hours?", filled: true, user_id: b.id, tags: "basic, personality, PIDK" )
Icebreaker.create!(content: "Do you work better with or without music? What are you listening to while you work?", filled: true, user_id: b.id, tags: "basic, personality, work" )
Icebreaker.create!(content: "What’s a TV show you recommend to everyone?", filled: true, user_id: b.id, tags: "basic, pop culture, television" )
Icebreaker.create!(content: "Where did you grow up? What did you like most about it? Dislike most?", filled: true, user_id: b.id, tags: "basic, personality, PIDK" )
Icebreaker.create!(content: "What’s the most useful thing you own?", filled: true, user_id: b.id, tags: "basic, PIDK, work" )
Icebreaker.create!(content: "You’ve been teleported to the middle ages. How do you make a living there?", filled: true, user_id: b.id, tags: "funny, history, PIDK" )
Icebreaker.create!(content: "If you could have an animal sidekick, what animal would it be? Why?", filled: true, user_id: b.id, tags: "animals, super powers" )
Icebreaker.create!(content: "What do you value most in a friendship?", filled: true, user_id: b.id, tags: "basic, personality, life" )
Icebreaker.create!(content: "What’s something that you’ve never learned to do that you want to?", filled: true, user_id: b.id, tags: "basic, personality, life" )
Icebreaker.create!(content: "If you could go back in time 10,000 years ago and make a cave painting to confuse everyone in the future, what would you draw?", filled: true, user_id: b.id, tags: "funny, history, PIDK" )
Icebreaker.create!(content: "What’s your favorite thing about the place you live?", filled: true, user_id: b.id, tags: "basic, personality, life" )
Icebreaker.create!(content: "If you could instantly know any other language, which would it be and why?", filled: true, user_id: b.id, tags: "basic, personality, life" )
Icebreaker.create!(content: "What is your go-to chair sitting position? Cross-legged, slouched, backwards?", filled: true, user_id: b.id, tags: "basic, work, life" )
Icebreaker.create!(content: "What is your go-to stress relief strategy?", filled: true, user_id: b.id, tags: "basic, personality, work" )
Icebreaker.create!(content: "What’s a sauce, condiment or dressing you couldn’t live without?", filled: true, user_id: b.id, tags: "basic, funny, food" )
Icebreaker.create!(content: "What’s an adult problem nobody prepared you for?", filled: true, user_id: b.id, tags: "work, funny, childhood" )
Icebreaker.create!(content: "What’s one of your pet peeves?", filled: true, user_id: b.id, tags: "basic, life" )
Icebreaker.create!(content: "If you could go on tour with any musician or group, past or present, who would it be?", filled: true, user_id: b.id, tags: "if you could, music, funny" )
Icebreaker.create!(content: "How do you laugh via text? LOL, LMFAO, haha?", filled: true, user_id: b.id, tags: "remote, pop culture, communication, funny" )
Icebreaker.create!(content: "What’s the best theme-park ride you've ever been on?", filled: true, user_id: b.id, tags: "history, favorites, childhood" )
Icebreaker.create!(content: "If you could add a face to Mount Rushmore, who would you add?", filled: true, user_id: b.id, tags: "work, basic, history" )
Icebreaker.create!(content: "If you could turn the ocean into any other substance than water, what would it be and why?", filled: true, user_id: b.id, tags: "funny, PIDK, personality" )
Icebreaker.create!(content: "Who is the most interesting stranger you've ever had the chance to meet?", filled: true, user_id: b.id, tags: "history, funny, PIDK" )
Icebreaker.create!(content: "If you could change your name, what would you change it to and why?", filled: true, user_id: b.id, tags: "work, basic" )
Icebreaker.create!(content: "Do you play any musical instruments? If not, which would you most like to play?", filled: true, user_id: b.id, tags: "work, favorite, life" )
Icebreaker.create!(content: "How do you break awkward silences?", filled: true, user_id: b.id, tags: "work, funny, PIDK" )
Icebreaker.create!(content: "Are you a morning person or a night person?", filled: true, user_id: b.id, tags: "work, would you rather, basic" )
Icebreaker.create!(content: "What childhood show, movie, or character were you most afraid of as a kid?", filled: true, user_id: b.id, tags: "television, childhood, PIDK" )
Icebreaker.create!(content: "What was the first concert you ever went to? If you can't remember, what album did you first purchase?", filled: true, user_id: b.id, tags: "basic, life, music" )
Icebreaker.create!(content: "What’s a weird fact you happen to know?", filled: true, user_id: b.id, tags: "funny, personality, PIDK" )
Icebreaker.create!(content: "Which Disney character’s story does your life most resemble?", filled: true, user_id: b.id, tags: "childhood, pop culture" )
Icebreaker.create!(content: "What’s your best idea for a reality TV show?", filled: true, user_id: b.id, tags: "funny, television, PIDK" )
Icebreaker.create!(content: "Who is your celebrity look-alike?", filled: true, user_id: b.id, tags: "basic, pop culture, life" )
Icebreaker.create!(content: "What commercial jingle gets stuck in your head all the time?", filled: true, user_id: b.id, tags: "funny, life, PIDK" )
Icebreaker.create!(content: "If you could only eat at one restaurant forever, what restaurant would it be?", filled: true, user_id: b.id, tags: "if you could, basic, food" )
Icebreaker.create!(content: "If you had to be an animal, which animal would you be?", filled: true, user_id: b.id, tags: "if you could, animals" )
Icebreaker.create!(content: "What food or food combination do you love that a lot of people might find a little odd?", filled: true, user_id: b.id, tags: "basic, food, favorites" )
Icebreaker.create!(content: " What are some of your favorite games to play?, either virtual or live?", filled: true, user_id: b.id, tags: "basic, favorites, life" )
Icebreaker.create!(content: "How could carousels be spiced up so they are more exciting?", filled: true, user_id: b.id, tags: "funny, animals, PIDK" )
Icebreaker.create!(content: "What subjects should be taught in school that aren’t?", filled: true, user_id: b.id, tags: "basic, childhood, life" )
Icebreaker.create!(content: "What pets did you have growing up?", filled: true, user_id: b.id, tags: "basic, life" )
Icebreaker.create!(content: "What do you resent paying for most?", filled: true, user_id: b.id, tags: "basic, life" )
Icebreaker.create!(content: "What weird quirks did you pick up from your childhoom home?", filled: true, user_id: b.id, tags: "basic, life, childhood" )
Icebreaker.create!(content: "Besides war and diplomacy, what would be the best way for countries to settle disputes?", filled: true, user_id: b.id, tags: "funny, potentially sensitive, PIDK" )
Icebreaker.create!(content: "WWhat’s your favorite thing about the area/city/state you live in?", filled: true, user_id: b.id, tags: "basic, life" )
Icebreaker.create!(content: "Do you prefer pens or pencils? ", filled: true, user_id: b.id, tags: "basic, would you rather, work" )
Icebreaker.create!(content: "What’s the scariest horror movie you've seen or heard about?", filled: true, user_id: b.id, tags: "favorites, pop culture, PIDK")
Icebreaker.create!(content: "What’s your morning drink of choice? ", filled: true, user_id: b.id, tags: "basic, work, favorites" )
Icebreaker.create!(content: "What luxury is totally worth the price?", filled: true, user_id: b.id, tags: "basic, life" )
Icebreaker.create!(content: "What do you think is the purpose of dreaming?", filled: true, user_id: b.id, tags: "thought-provoking, PIDK" )
Icebreaker.create!(content: "Is it possible to live a normal life and not ever tell a lie?", filled: true, user_id: b.id, tags: "thought-provoking, PIDK" )
Icebreaker.create!(content: "Where does your self-worth come from?", filled: true, user_id: b.id, tags: "thought-provoking, PIDK" )
Icebreaker.create!(content: "Would things get better or worse if humans focused on what was going well rather than what’s going wrong?", filled: true, user_id: b.id, tags: "thought-provoking, PIDK" )
Icebreaker.create!(content: "Is it better for a person to have a broad knowledge base or a deep knowledge base?", filled: true, user_id: b.id, tags: "thought-provoking, PIDK" )
Icebreaker.create!(content: "Is it better to be a big fish in a small pond or a small fish in a big pond?", filled: true, user_id: b.id, tags: "thought-provoking, PIDK" )
Icebreaker.create!(content: "What three words best describe you?", filled: true, user_id: b.id, tags: "basic, life" )
Icebreaker.create!(content: "What’s your favorite number? Why?", filled: true, user_id: b.id, tags: "basic, favorites, PIDK" )
Icebreaker.create!(content: "Do you have any pets? What are their names?", filled: true, user_id: b.id, tags: "basic, animals, life" )
Icebreaker.create!(content: "What did you do on your last vacation?", filled: true, user_id: b.id, tags: "basic, life" )
Icebreaker.create!(content: "What were you really into when you were a kid?", filled: true, user_id: b.id, tags: "basic, childhood, life" )
Icebreaker.create!(content: "What is a controversial opinion you have?", filled: true, user_id: b.id, tags: "funny, potentially sensitive, PIDK" )
Icebreaker.create!(content: "What’s the best sitcom past or present?", filled: true, user_id: b.id, tags: "television, pop culture, basic" )
Icebreaker.create!(content: "What do you think about game shows? Do you have a favorite one?", filled: true, user_id: b.id, tags: "television, pop culture, basic" )
Icebreaker.create!(content: "What kind of case do you have for your phone? Why did you choose it?", filled: true, user_id: b.id, tags: "basic, life" )
Icebreaker.create!(content: "What defines a sport? Is fishing a sport? How about video game tournaments?", filled: true, user_id: b.id, tags: "funny, PIDK, thought-provoking" )
Icebreaker.create!(content: "What technology from a science fiction movie would you most like to have?", filled: true, user_id: b.id, tags: "funny, PIDK, pop culture" )    
Icebreaker.create!(content: "Is teaching a skill that can be taught?", filled: true, user_id: b.id, tags: "thought-provoking, PIDK, life" )    
Icebreaker.create!(content: "If you had a personal mascot, what would your mascot be?", filled: true, user_id: b.id, tags: "funny, PIDK, animals" )
Icebreaker.create!(content: "Time freezes for everyone but you for one day. What do you do?", filled: true, user_id: b.id, tags: "funny, PIDK, life" )
Icebreaker.create!(content: "What is the best food you have ever eaten?", filled: true, user_id: b.id, tags: "basic, food, life" )
Icebreaker.create!(content: "What weird or useless talent do you have?", filled: true, user_id: b.id, tags: "funny, PIDK, life" )
Icebreaker.create!(content: "What is your work-at-home uniform?", filled: true, user_id: b.id, tags: "basic, work, life" )
Icebreaker.create!(content: "Is there a skill you stopped working on that you would like to revisit?", filled: true, user_id: b.id, tags: "fbasic, work, life" )
Icebreaker.create!(content: "If you were to choose a well-known axiom or slogan for your life, what would it be?", filled: true, user_id: b.id, tags: "funny, basic, life" )
Icebreaker.create!(content: "Do you collect anything?", filled: true, user_id: b.id, tags: "work, basic, life" )
Icebreaker.create!(content: "What’s your go-to karaoke song?", filled: true, user_id: b.id, tags: "work, basic, life" )
Icebreaker.create!(content: "Do you enjoy the outdoors? What’s your favorite outdoor activity?", filled: true, user_id: b.id, tags: "basic, life" )
Icebreaker.create!(content: "What’s your favorite seat on an airplane?", filled: true, user_id: b.id, tags: "favorites, basic, life" )
Icebreaker.create!(content: "What is your favorite magical or mythological creature?", filled: true, user_id: b.id, tags: "history, favorites, basic" )
Icebreaker.create!(content: "Sweet, salty, or sour?", filled: true, user_id: b.id, tags: "food, favorites, basic" )
Icebreaker.create!(content: "Do you set New Years Resolutions? Why or why not?", filled: true, user_id: b.id, tags: "basic, work, life" )
Icebreaker.create!(content: "What “old person” things do you do?", filled: true, user_id: b.id, tags: "funny, basic, life" )

    # Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
