# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
default=User.create!(id: default, username: 'default', password: 'default')
b=User.create!(username: 'bananabb', password: "acffff")

Icebreaker.create!(content: "What fictional family would you most like to join?", flames: 0,tags: "media, pop culture, television", favorite: false, category: "question")
Icebreaker.create!(content: "Do you love working from home or would you rather be in the office? Is there a balance of both that you like best?", flames: 0,tags: "remote, virtual, WFH", favorite: false, category: "question")
Icebreaker.create!(content: "What’s your number one tip for combating distractions when working from home?", flames: 0,tags: "remote, virtual, WFH, motivation", favorite: false, category: "question")
Icebreaker.create!(content: "What’s the last great TV show or movie you watched?", flames: 0,tags: "remote, virtual, television, pop culture", favorite: false, category: "question")
Icebreaker.create!(content: "What is your most used emoji?", flames: 0,tags: "remote, pop culture, communication, funny", favorite: false )
Icebreaker.create!(content: "If you were a wrestler what would be your entrance theme song?", flames: 0,tags: "pop culture, media, funny", favorite: false, category: "question")
Icebreaker.create!(content: "If you could bring back any fashion trend what would it be?", flames: 0,tags: "pop culture, fashion, trends", favorite: false, category: "question")
Icebreaker.create!(content: "You have your own late night talk show, who do you invite as your first guest?", flames: 0,tags: "pop culture, media, funny", favorite: false, category: "question")
Icebreaker.create!(content: "If you had to eat one meal everyday for the rest of your life what would it be?", flames: 0,tags: "funny, childhood, favorites")
Icebreaker.create!(content: "If you were left on a deserted island with either your worst enemy or no one, which would you choose? Why?", flames: 0, tags: "funny, would you rather")
Icebreaker.create!(content: "What’s the best piece of advice you’ve ever been given?", flames: 0,tags: "work, teamwork, motivation", favorite: false, category: "question")
Icebreaker.create!(content: "What would the title of your autobiography be?", flames: 0,tags: "remote, literature, motivation", favorite: false, category: "question")
Icebreaker.create!(content: "Who is your favorite Disney hero or heroine? Would you trade places with them?", flames: 0,tags: "pop culture, media, childhood", favorite: false, category: "question")
Icebreaker.create!(content: "What languages do you know how to speak?", flames: 0,tags: "basic, work", favorite: false, category: "question")
Icebreaker.create!(content: "Are you a cat person or a dog person?", flames: 0,tags: "basic, animals, would you rather", favorite: false, category: "question")
Icebreaker.create!(content: "You can have an unlimited supply of one thing for the rest of your life, what is it? Sushi? Scotch Tape?", flames: 0,tags: "WWYD, unusual, funny", favorite: false, category: "question")
Icebreaker.create!(content: "If you could live anywhere in the world for a year, where would it be?", flames: 0, tags: "if you could, work")
Icebreaker.create!(content: "If you could choose any two famous people to have dinner with who would they be?", flames: 0,tags: "if you could, pop culture, media, history", favorite: false, category: "question")
Icebreaker.create!(content: "If you could be any animal in the world, what animal would you choose to be?", flames: 0,tags: "if you could, favorites, animals", favorite: false, category: "question")
Icebreaker.create!(content: "If you could instantly become an expert in something, what would it be?", flames: 0,tags: "if you could, work, motivation", favorite: false, category: "question")
Icebreaker.create!(content: "Would you rather live in the ocean or on the moon?", flames: 0,tags: "would you rather, funny, life", favorite: false, category: "question")
Icebreaker.create!(content: "Would you rather meet your travel back in time to meet your ancestors or to the future to meet your descendants?", flames: 0,tags: "would you rather, family, life", favorite: false, category: "question")
Icebreaker.create!(content: "Would you rather live where it only snows or the temperature never falls below 100 degrees?", flames: 0,tags: "would you rather, basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "Did you attend college? What was your major, or what would it have been?", flames: 0,tags: "history, life, potentially sensitive", favorite: false, category: "question")
Icebreaker.create!(content: "What was your dream job when you were a kid?", flames: 0,tags: "childhood, history, work", favorite: false, category: "question")
Icebreaker.create!(content: "Are there any interesting things your name spells with the letters rearranged?", flames: 0,tags: "PIDK, general", favorite: false, category: "question")
Icebreaker.create!(content: "On what reality show would you most like to appear?", flames: 0,tags: "if you could, pop culture, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: " Which of Snow White’s seven dwarfs describes you best (Bashful, Doc, Dopey, Grumpy, Happy, Sleepy or Sneezy)?", flames: 0,tags: "pop culture, personality", favorite: false, category: "question")
Icebreaker.create!(content: "Are you a listener or a talker?", flames: 0,tags: "would you rather, personality", favorite: false, category: "question")
Icebreaker.create!(content: "If you could only listen to one album for the rest of your life, what would it be?", flames: 0,tags: "if you could, favorites, music", favorite: false, category: "question")
Icebreaker.create!(content: "What was the worst movie you’ve ever watched?", flames: 0,tags: "favorites, pop culture, media, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "Would you rather have invisibility or flight?", flames: 0,tags: "would you rather, super powers")
Icebreaker.create!(content: "Would you prefer to always be slightly late or always be an hour early?", flames: 0,tags: "would you rather, personality", favorite: false, category: "question")
Icebreaker.create!(content: "What was your first job?", flames: 0,tags: "personality, history, basic", favorite: false, category: "question")
Icebreaker.create!(content: "What year would you visit if you had a time machine?", flames: 0,tags: "if you could, history, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "What's your favorite breakfast cereal or breakfast food?", flames: 0,tags: "favorites, basic", favorite: false, category: "question")
Icebreaker.create!(content: "What’s something new or interesting you’ve learned recently?", flames: 0,tags: "personality, history, basic", favorite: false, category: "question")
Icebreaker.create!(content: "If you could safely eat any inedible object, what would it be?", flames: 0,tags: "funny, personality, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "If you did not have to sleep, how would you spend the extra 8 hours?", flames: 0,tags: "basic, personality, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "What season would you be? Why?", flames: 0,tags: "basic, personality", favorite: false, category: "question")
Icebreaker.create!(content: "If you did not have to sleep, how would you spend the extra 8 hours?", flames: 0,tags: "basic, personality, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "Do you work better with or without music? What are you listening to while you work?", flames: 0,tags: "basic, personality, work", favorite: false, category: "question")
Icebreaker.create!(content: "What’s a TV show you recommend to everyone?", flames: 0,tags: "basic, pop culture, television", favorite: false, category: "question")
Icebreaker.create!(content: "Where did you grow up? What did you like most about it? Dislike most?", flames: 0,tags: "basic, personality, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "What’s the most useful thing you own?", flames: 0,tags: "basic, PIDK, work", favorite: false, category: "question")
Icebreaker.create!(content: "You’ve been teleported to the middle ages. How do you make a living there?", flames: 0,tags: "funny, history, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "If you could have an animal sidekick, what animal would it be? Why?", flames: 0,tags: "animals, super powers", favorite: false, category: "question")
Icebreaker.create!(content: "What do you value most in a friendship?", flames: 0,tags: "basic, personality, life", favorite: false, category: "question")
Icebreaker.create!(content: "What’s something that you’ve never learned to do that you want to?", flames: 0,tags: "basic, personality, life", favorite: false, category: "question")
Icebreaker.create!(content: "If you could go back in time 10,000 years ago and make a cave painting to confuse everyone in the future, what would you draw?", flames: 0,tags: "funny, history, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "What’s your favorite thing about the place you live?", flames: 0,tags: "basic, personality, life", favorite: false, category: "question")
Icebreaker.create!(content: "If you could instantly know any other language, which would it be and why?", flames: 0,tags: "basic, personality, life", favorite: false, category: "question")
Icebreaker.create!(content: "What is your go-to chair sitting position? Cross-legged, slouched, backwards?", flames: 0,tags: "basic, work, life", favorite: false, category: "question")
Icebreaker.create!(content: "What is your go-to stress relief strategy?", flames: 0,tags: "basic, personality, work", favorite: false, category: "question")
Icebreaker.create!(content: "What’s a sauce, condiment or dressing you couldn’t live without?", flames: 0,tags: "basic, funny, food", favorite: false, category: "question")
Icebreaker.create!(content: "What’s an adult problem nobody prepared you for?", flames: 0,tags: "work, funny, childhood", favorite: false, category: "question")
Icebreaker.create!(content: "What’s one of your pet peeves?", flames: 0,tags: "basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "If you could go on tour with any musician or group, past or present, who would it be?", flames: 0,tags: "if you could, music, funny", favorite: false, category: "question")
Icebreaker.create!(content: "How do you laugh via text? LOL, LMFAO, haha?", flames: 0,tags: "remote, pop culture, communication, funny", favorite: false, category: "question")
Icebreaker.create!(content: "What’s the best theme-park ride you've ever been on?", flames: 0,tags: "history, favorites, childhood", favorite: false, category: "question")
Icebreaker.create!(content: "If you could add a face to Mount Rushmore, who would you add?", flames: 0,tags: "work, basic, history", favorite: false, category: "question")
Icebreaker.create!(content: "If you could turn the ocean into any other substance than water, what would it be and why?", flames: 0,tags: "funny, PIDK, personality", favorite: false, category: "question")
Icebreaker.create!(content: "Who is the most interesting stranger you've ever had the chance to meet?", flames: 0, tags: "history, funny, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "If you could change your name, what would you change it to and why?", flames: 0, tags: "work, basic", favorite: false, category: "question")
Icebreaker.create!(content: "Do you play any musical instruments? If not, which would you most like to play?", flames: 0, tags: "work, favorite, life", favorite: false, category: "question")
Icebreaker.create!(content: "How do you break awkward silences?", flames: 0, tags: "work, funny, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "Are you a morning person or a night person?", flames: 0, tags: "work, would you rather, basic", favorite: false, category: "question")
Icebreaker.create!(content: "What childhood show, movie, or character were you most afraid of as a kid?", flames: 0, tags: "television, childhood, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "What was the first concert you ever went to? If you can't remember, what album did you first purchase?", flames: 0, tags: "basic, life, music", favorite: false, category: "question")
Icebreaker.create!(content: "What’s a weird fact you happen to know?", flames: 0, tags: "funny, personality, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "Which Disney character’s story does your life most resemble?", flames: 0, tags: "childhood, pop culture", favorite: false, category: "question")
Icebreaker.create!(content: "What’s your best idea for a reality TV show?", flames: 0, tags: "funny, television, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "Who is your celebrity look-alike?", flames: 0, tags: "basic, pop culture, life", favorite: false, category: "question")
Icebreaker.create!(content: "What commercial jingle gets stuck in your head all the time?", flames: 0, tags: "funny, life, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "If you could only eat at one restaurant forever, what restaurant would it be?", flames: 0, tags: "if you could, basic, food", favorite: false, category: "question")
Icebreaker.create!(content: "If you had to be an animal, which animal would you be?", flames: 0, tags: "if you could, animals", favorite: false, category: "question")
Icebreaker.create!(content: "What food or food combination do you love that a lot of people might find a little odd?", flames: 0, tags: "basic, food, favorites", favorite: false, category: "question")
Icebreaker.create!(content: " What are some of your favorite games to play?, either virtual or live?", flames: 0, tags: "basic, favorites, life", favorite: false, category: "question")
Icebreaker.create!(content: "How could carousels be spiced up so they are more exciting?", flames: 0, tags: "funny, animals, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "What subjects should be taught in school that aren’t?", flames: 0, tags: "basic, childhood, life", favorite: false, category: "question")
Icebreaker.create!(content: "What pets did you have growing up?", flames: 0, tags: "basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "What do you resent paying for most?", flames: 0, tags: "basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "What weird quirks did you pick up from your childhoom home?", flames: 0, tags: "basic, life, childhood", favorite: false, category: "question")
Icebreaker.create!(content: "Besides war and diplomacy, what would be the best way for countries to settle disputes?", flames: 0, tags: "funny, potentially sensitive, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "WWhat’s your favorite thing about the area/city/state you live in?", flames: 0, tags: "basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "Do you prefer pens or pencils? ", flames: 0, tags: "basic, would you rather, work", favorite: false, category: "question")
Icebreaker.create!(content: "What’s the scariest horror movie you've seen or heard about?", flames: 0, tags: "favorites, pop culture, PIDK")
Icebreaker.create!(content: "What’s your morning drink of choice? ", flames: 0, tags: "basic, work, favorites", favorite: false, category: "question")
Icebreaker.create!(content: "What luxury is totally worth the price?", flames: 0, tags: "basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "What do you think is the purpose of dreaming?", flames: 0, tags: "thought-provoking, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "Is it possible to live a normal life and not ever tell a lie?", flames: 0, tags: "thought-provoking, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "Where does your self-worth come from?", flames: 0, tags: "thought-provoking, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "Would things get better or worse if humans focused on what was going well rather than what’s going wrong?", flames: 0, tags: "thought-provoking, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "Is it better for a person to have a broad knowledge base or a deep knowledge base?", flames: 0, tags: "thought-provoking, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "Is it better to be a big fish in a small pond or a small fish in a big pond?", flames: 0, tags: "thought-provoking, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "What three words best describe you?", flames: 0, tags: "basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "What’s your favorite number? Why?", flames: 0, tags: "basic, favorites, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "Do you have any pets? What are their names?", flames: 0, tags: "basic, animals, life", favorite: false, category: "question")
Icebreaker.create!(content: "What did you do on your last vacation?", flames: 0, tags: "basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "What were you really into when you were a kid?", flames: 0, tags: "basic, childhood, life", favorite: false, category: "question")
Icebreaker.create!(content: "What is a controversial opinion you have?", flames: 0, tags: "funny, potentially sensitive, PIDK", favorite: false, category: "question")
Icebreaker.create!(content: "What’s the best sitcom past or present?", flames: 0, tags: "television, pop culture, basic", favorite: false, category: "question")
Icebreaker.create!(content: "What do you think about game shows? Do you have a favorite one?", flames: 0, tags: "television, pop culture, basic", favorite: false, category: "question")
Icebreaker.create!(content: "What kind of case do you have for your phone? Why did you choose it?", flames: 0, tags: "basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "What defines a sport? Is fishing a sport? How about video game tournaments?", flames: 0, tags: "funny, PIDK, thought-provoking", favorite: false, category: "question")
Icebreaker.create!(content: "What technology from a science fiction movie would you most like to have?", flames: 0, tags: "funny, PIDK, pop culture", favorite: false, category: "question") 
Icebreaker.create!(content: "Is teaching a skill that can be taught?", flames: 0, tags: "thought-provoking, PIDK, life", favorite: false, category: "question") 
Icebreaker.create!(content: "If you had a personal mascot, what would your mascot be?", flames: 0, tags: "funny, PIDK, animals", favorite: false, category: "question")
Icebreaker.create!(content: "Time freezes for everyone but you for one day. What do you do?", flames: 0, tags: "funny, PIDK, life", favorite: false, category: "question")
Icebreaker.create!(content: "What is the best food you have ever eaten?", flames: 0, tags: "basic, food, life", favorite: false, category: "question")
Icebreaker.create!(content: "What weird or useless talent do you have?", flames: 0, tags: "funny, PIDK, life", favorite: false, category: "question")
Icebreaker.create!(content: "What is your work-at-home uniform?", flames: 0, tags: "basic, work, life", favorite: false, category: "question")
Icebreaker.create!(content: "Is there a skill you stopped working on that you would like to revisit?", flames: 0, tags: "fbasic, work, life", favorite: false, category: "question")
Icebreaker.create!(content: "If you were to choose a well-known axiom or slogan for your life, what would it be?", flames: 0, tags: "funny, basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "Do you collect anything?", flames: 0, tags: "work, basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "What’s your go-to karaoke song?", flames: 0, tags: "work, basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "Do you enjoy the outdoors? What’s your favorite outdoor activity?", flames: 0, tags: "basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "What’s your favorite seat on an airplane?", flames: 0, tags: "favorites, basic, life", favorite: false, category: "question")
Icebreaker.create!(content: "What is your favorite magical or mythological creature?", flames: 0, tags: "history, favorites, basic", favorite: false, category: "question")
Icebreaker.create!(content: "Sweet, salty, or sour?", flames: 0, tags: "food, favorites, basic", favorite: false, category: "question")
Icebreaker.create!(content: "Do you set New Years Resolutions? Why or why not?", flames: 0, tags: "basic, work, life", favorite: false, category: "question")
Icebreaker.create!(content: "What “old person” things do you do?", flames: 0, tags: "funny, basic, life", favorite: false, category: "question")
# Examples:
#
# flames: 0,  movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# flames: 0,  Character.create(name: 'Luke', movie: movies.first)
